# Generated by Django 5.1.6 on 2025-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_study_session_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_session',
            name='name',
        ),
        migrations.AddField(
            model_name='study_session',
            name='campus_location',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='study_session',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='study_session',
            name='duration',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='study_session',
            name='preferences',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='study_session',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='study_session',
            name='course',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
