# Generated by Django 5.1.6 on 2025-04-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_study_session_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_session',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
    ]
