# Generated by Django 5.1.6 on 2025-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_study_session_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_session',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
